---
- name: "LOW | RHEL-07-020200 | PATCH | The operating system must remove all software components after updated versions have been installed."
  lineinfile:
      dest: /etc/yum.conf
      regexp: ^#?clean_requirements_on_remove
      line: clean_requirements_on_remove=1
      insertafter: '\[main\]'
  when: rhel_07_020200
  tags:
      - RHEL-07-020200

- name: "LOW | RHEL-07-020300 | PATCH | All Group Identifiers (GIDs) referenced in the /etc/passwd file must be defined in the /etc/group file."
  block:
      - name: "LOW | RHEL-07-020300 | PATCH | Check /etc/passwd entries"
        shell: pwck -r | grep 'no group' | awk '{ gsub("[:\47]",""); print $2}'
        changed_when: no
        failed_when: no
        check_mode: no
        register: passwd_gid_check

      - name: "LOW | RHEL-07-020300 | PATCH | Print warning about users with invalid GIDs missing GID entries in /etc/group"
        debug:
            msg: "WARNING: The following users have non-existent GIDs: {{ passwd_gid_check.stdout_lines | join (', ')}}"
        changed_when:
            - rhel7stig_audit_complex
        when: passwd_gid_check.stdout_lines
  when:
      - rhel_07_020300
      - rhel7stig_complex
  tags:
      - RHEL-07-020300
      - complexity-high
      - passwd

- name: |
      "LOW | RHEL-07-021022 | PATCH | The Red Hat Enterprise Linux operating system must mount /dev/shm with the nodev option."
      "LOW | RHEL-07-021023 | PATCH | The Red Hat Enterprise Linux operating system must mount /dev/shm with the nosuid option."
      "LOW | RHEL-07-021024 | PATCH | The Red Hat Enterprise Linux operating system must mount /dev/shm with the noexec option."
  mount:
      path: /dev/shm
      state: mounted
      src: "{{ dev_shm_mount.device|default('tmpfs') }}"
      fstype: "{{ dev_shm_mount.fstype|default('tmpfs') }}"
      opts: "{{ dev_shm_mount_opts }}"
  when: rhel_07_021022 or rhel_07_021023 or rhel_07_021024
  vars:
      dev_shm_mount: "{{ ansible_mounts | json_query('[?mount == `/dev/shm`] | [0]') }}"
      dev_shm_mount_opts: "{{ dev_shm_mount.options | default('defaults') }},nodev,nosuid{{ (rhel_07_021024) | ternary(',noexec', '') }}"
  tags:
      - RHEL-07-021022
      - RHEL-07-021023
      - RHEL-07-021024

- name: "LOW | RHEL-07-021310 | PATCH | A separate file system must be used for user home directories (such as /home or an equivalent)."
  debug:
      msg: "WARNING: /home is not mounted on a separate partition"
  changed_when:
      - rhel7stig_audit_complex
  when:
      - not rhel7stig_system_is_container
      - rhel_07_021310
      - rhel7stig_complex
      - ansible_mounts | selectattr('mount', 'match', '^/home$') | list | length == 0
  tags:
      - RHEL-07-021310
      - complexity-high
      - mount
      - home

- name: "LOW | RHEL-07-021320 | PATCH | The system must use a separate file system for /var."
  debug:
      msg: "WARNING: /var is not mounted on a separate partition"
  changed_when:
      - rhel7stig_audit_complex
  when:
      - not rhel7stig_system_is_container
      - rhel_07_021320
      - rhel7stig_complex
      - ansible_mounts | selectattr('mount', 'match', '^/var$') | list | length == 0
  tags:
      - RHEL-07-021320
      - complexity-high
      - mount
      - var

- name: "LOW | RHEL-07-021330 | PATCH | The system must use a separate file system for the system audit data path."
  debug:
      msg: "WARNING: /var/log/audit is not mounted on a separate partition"
  changed_when:
      - rhel7stig_audit_complex
  when:
      - not rhel7stig_system_is_container
      - rhel_07_021330
      - rhel7stig_complex
      - ansible_mounts | selectattr('mount', 'match', '^/var/log/audit$') | list | length == 0
  tags:
      - RHEL-07-021330
      - complexity-high
      - mount
      - auditd

- name: "LOW | RHEL-07-021340 | PATCH | The system must use a separate file system for /tmp (or equivalent)."
  systemd:
      name: tmp.mount
      daemon_reload: "{{ rhel7stig_systemd_daemon_reload }}"
      enabled: yes
      masked: no
      state: "{{ rhel7stig_service_started }}"
  when:
      - rhel_07_021340
      - not (rhel7stig_system_is_chroot and rhel7stig_system_is_container)
  tags:
      - RHEL-07-021340
      - mount
      - tmp

- block:
      - name: "LOW | RHEL-07-021600 | PATCH | The file integrity tool must be configured to verify Access Control Lists (ACLs).  Gather offending lines"
        shell: |
          /usr/bin/awk '/^[^#]+=/ { split($0, p, "="); gsub(/ /, "", p[1]); gsub(/ /, "", p[2]); r[p[1]] = p[2]; } /^[^#=!@]/ && !/=/ { x=$2; for (v in r) { c = sprintf("(^|+| )%s(+| |$)", v); gsub(c, r[v], x); } if ($0) { if (x !~ /acl/) { print $1; f++ } } }' /etc/aide.conf
        register: rhel_07_021600_audit

      - name: "LOW | RHEL-07-021600 | PATCH | The file integrity tool must be configured to verify Access Control Lists (ACLs).  Change to acl verify"
        replace:
          path: /etc/aide.conf
          regexp: ^({{ item | regex_escape() }})(\s+)(.*)
          replace: '\1\2\3+acl'
        with_items: "{{ rhel_07_021600_audit.stdout_lines }}"
  when: rhel_07_021600
  tags:
      - RHEL-07-021600

- block:
      - name: "LOW | RHEL-07-021610 | PATCH | The file integrity tool must be configured to verify extended attributes.  Gather offending lines"
        shell: |
          /usr/bin/awk '/^[^#]+=/ { split($0, p, "="); gsub(/ /, "", p[1]); gsub(/ /, "", p[2]); r[p[1]] = p[2]; } /^[^#=!@]/ && !/=/ { x=$2; for (v in r) { c = sprintf("(^|+| )%s(+| |$)", v); gsub(c, r[v], x); } if ($0) { if (x !~ /xattrs/) { print $1; f++ } } }' /etc/aide.conf
        register: rhel_07_021610_audit

      - name: "LOW | RHEL-07-021610 | PATCH | The file integrity tool must be configured to verify extended attributes.  Change to xattrs verify"
        replace:
          path: /etc/aide.conf
          regexp: ^({{ item | regex_escape() }})(\s+)(.*)
          replace: '\1\2\3+xattrs'
        with_items: "{{ rhel_07_021610_audit.stdout_lines }}"
  when: rhel_07_021610
  tags:
      - RHEL-07-021610

- block:
      - name: "LOW | RHEL-07-021620 | PATCH | Configure the file integrity tool to use FIPS 140-2 cryptographic hashes for validating file and directory contents.  Gather offending lines"
        shell: |
          /usr/bin/awk '/^[^#]+=/ { split($0, p, "="); gsub(/ /, "", p[1]); gsub(/ /, "", p[2]); r[p[1]] = p[2]; } /^[^#=!@]/ && !/=/ { x=$2; for (v in r) { c = sprintf("(^|+| )%s(+| |$)", v); gsub(c, r[v], x); } if ($0) { if (x !~ /sha512/) { print $1; f++ } } } END { if (f) { print "fail" } else { print "pass" } }' /etc/aide.conf
        register: rhel_07_021620_audit

      - name: "LOW | RHEL-07-021620 | PATCH | Configure the file integrity tool to use FIPS 140-2 cryptographic hashes for validating file and directory contents.  Change to sha512 verify"
        replace:
          path: /etc/aide.conf
          regexp: ^({{ item | regex_escape() }})(\s+)(.*)
          replace: '\1\2\3+sha512'
        with_items: "{{ rhel_07_021620_audit.stdout_lines }}"
  when: rhel_07_021620
  tags:
      - RHEL-07-021620

- name: "LOW | RHEL-07-040000 | PATCH | The operating system must limit the number of concurrent sessions to 10 for all accounts and/or account types."
  lineinfile:
      state: present
      dest: /etc/security/limits.conf
      insertbefore: '^# End of file'
      regexp: '^\*.*maxlogins'
      line: '*               hard    maxlogins       {{ rhel7stig_maxlogins }}'
  when: rhel_07_040000
  tags:
      - RHEL-07-040000

- name: "LOW | RHEL-07-040530 | PATCH | The system must display the date and time of the last successful account logon upon logon."
  blockinfile:
      state: present
      path: /etc/pam.d/postlogin
      insertafter: '^# User changes will be destroyed'
      block: |
          ### RHEL-07-040530 ###
          session required pam_lastlog.so showfailed
  when: rhel_07_040530
  tags:
      - RHEL-07-040530

- name: "LOW | RHEL-07-040600 | PATCH | For systems using DNS resolution, at least two name servers must be configured."
  command: "true"
  changed_when: no
  when: rhel_07_040600
  tags:
      - RHEL-07-040600
      - notimplemented
